---
title: "lab9_part2"
author: "R. Spellenberg"
date: "2023-03-18"
output: 
  html_document:
    code_folding: hide
---

```{r setup, echo = TRUE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
```

## Useful function in `stringr` (built into tidyverse)

### detect a pattern with `stringr::str_detect()`

```{r}
### make a practice vector
vec <- c('   A Unicorn      Fish',
         ' add   cornmeal',
         '    French FRIES',
         '   acorn squash123    ')

### try detecting some patterns
str_detect(vec, pattern = 'corn')
str_detect(vec, pattern = 'fish') ### capitalization is important
str_to_lower(vec) %>% ### letters to lowercase
  str_detect(pattern = 'fish')
### There is also str_to_upper, str_to_title, and str_to_sentence

### let's extract some strings
str_extract(vec, pattern = 'corn')
str_extract(vec, pattern = '[a-z]')
str_extract(vec, pattern = '[A-Z]')
str_extract(vec, pattern = '[0-9]') %>% 
  as.numeric() ### if you need it as a number, not a character

str_extract(vec, pattern = '[a-z]+')

str_extract_all(vec, pattern = '[a-z]+')

```


```{r}
walk_subset <- starwars %>% 
  filter(str_detect(name, pattern = 'walk'))

str_replace(vec, pattern = 'corn', replacement = 'COOL')
str_replace_all(vec, pattern = 'a', replacement = 'ZZZ')

sw_tornado <- starwars %>% 
  mutate(name = str_replace(name, pattern = 'Sky', replacement = 'TORNADO'))

sw_wacky <- starwars %>% 
  mutate(name2 = str_replace(name, pattern = '(w|W)b?a.+', replacement = 'WACKY')) %>% 
  select(name, name2)
### look for a lower or uppercase w, 0 or 1 b's, .+ is the rest of the text
  
```


```{r}
str_trim(vec) ### gets rid of white space on the ends of the text/data
str_squish(vec) ### gets rid of white space between words
```


### Let's use these in combination

```{r}
sw_combo <- starwars %>% 
  filter(str_detect(name, 'Darth')) %>% 
  mutate(name = str_replace(name, pattern = 'Darth', replacement = 'Llama')) %>% 
  mutate(name = str_to_lower(name))
```

















